server:
  port: 8080

spring:
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member_system
    username: root
    password: root

  mvc:
    pathmatch:
        matching-strategy: ant_path_matcher


  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.lantu: debug

